---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Dependencies
  apt:
    pkg:
      - build-essential

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: xtables.tar.xz
    dest: ~/xtables

# Setup for xtables version 3.2
- name: Running configure
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - ./configure

- name: Running make
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - make

- name: Running make install
  command: 'make install chdir=~/xtables/xtables-addons-3.2'