---
- name: Update DNS
  become: yes
  shell: echo "nameserver 1.1.1.1" > /etc/resolv.conf

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Dependencies
  apt:
    pkg:
      - libnet-cidr-lite-perl
      - iptables-dev
      - xtables-addons-common
      - libtext-csv-xs-perl
      - pkg-config

- file:
    path: ~/xtables
    state: directory

- file:
    path: /usr/share/xt_geoip
    state: directory

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: xtables.tar.xz
    dest: ~/xtables

# Setup for xtables version 3.2
- name: Running configure
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - ./configure

- name: Running make
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - make

- name: Running make install
  command: 'make install chdir=~/xtables/xtables-addons-3.2'

- name: Extract Maxmind database files
  unarchive:
    src: GeoLite2-Country-CSV_20200114.zip
    dest: ~/xtables/xtables-addons-3.2/geoip

- name: Copy CSV files
  shell: cp ~/xtables/xtables-addons-3.2/geoip/GeoLite2-Country-CSV_20200114/*.csv ~/xtables/xtables-addons-3.2/geoip

- name: Build xtables
  shell: cd ~/xtables/xtables-addons-3.2/geoip; ./xt_geoip_build -D "/usr/share/xt_geoip" -S $(find . -type d -name "Geo*")