---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Dependencies
  apt:
    pkg:
      - build-essential
      - libmaxminddb-dev
      - unzip

- name: Extract nginx
  unarchive:
    src: nginx-{{ nginx_ver }}.tar.gz
    dest: ~/

- name: Extract openssl
  unarchive:
    src: openssl-{{ openssl_ver }}.tar.gz
    dest: ~/

- name: Extract pcre
  unarchive:
    src: pcre-{{ pcre_ver }}.tar.gz
    dest: ~/

- name: Extract zlib
  unarchive:
    src: zlib-{{ zlib_ver }}.tar.gz
    dest: ~/

- name: Extract geoip2 module
  unarchive:
    src: geoip2_module.zip
    dest: ~/

- name: Extract Maxmind database
  unarchive:
    src: Geolite.db.zip
    dest: ~/

- name: Running configure
  shell: cd ~/nginx-{{ nginx_ver }}; ./configure --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --sbin-path=/usr/sbin/nginx --pid-path=/run/nginx.pid --with-pcre=../pcre-{{ pcre_ver }} --with-openssl=../openssl-{{ openssl_ver }} --with-zlib=../zlib-{{ zlib_ver }} --with-http_ssl_module --modules-path=/usr/local/nginx/modules --add-module=../ngx_http_geoip2_module-master --without-http_geo_module

- name: Running make
  shell: cd ~/nginx-{{ nginx_ver }}; make

- name: Running make install
  shell: cd ~/nginx-{{ nginx_ver }}; make install

- name: Create Nginx systemd file
  copy:
    src: nginx.service
    dest: /lib/systemd/system/nginx.service

- name: Restart Nginx
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
