---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Dependencies
  apt:
    pkg:
      - build-essential

- name: Extract nginx
  unarchive:
    src: nginx-{{ nginx_ver }}.tar.gz
    dest: ~/nginx-{{ nginx_ver }}

- name: Extract openssl
  unarchive:
    src: openssl-{{ openssl_ver }}.tar.gz
    dest: ~/openssl-{{ openssl_ver }}

- name: Extract pcre
  unarchive:
    src: pcre-{{ pcre_ver }}.tar.gz
    dest: ~/pcre-{{ pcre_ver }}

- name: Extract zlib
  unarchive:
    src: zlib-{{ zlib_ver }}.tar.gz
    dest: ~/zlib- {{ zlib_ver }}

# Setup for xtables version 3.2
- name: Running configure
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - ./configure

- name: Running make
  command: '"{{ item }}" chdir=~/xtables/xtables-addons-3.2'
  with_items:
    - make

- name: Running make install
  command: 'make install chdir=~/xtables/xtables-addons-3.2'